### ISSUE TITLE
On the dropship module, after new order previous order id showing 2 times on the order page 

### ISSUE THREAD

**Issue by nikita-webkul** [bagisto/laravel-aliexpress-dropship#103]
**Bagisto:v1.3.2
dropship :v1.3.2**

**Description :**
1. Go to the admin end-> go to the dropship manager
2. go to the orders ->. after a new order, previous order id shows 2 times on the order page.

![image](https://github.com/bagisto/laravel-aliexpress-dropship/assets/146415222/b1803f5a-fc2b-4edb-8a80-dc4993932117)

**Comment by shivamwebkul** [comment]
Issue is fixed

**Comment by nikita-webkul** [comment]
yes fixed,

![Screenshot from 2024-05-07 16-12-07](https://github.com/bagisto/laravel-aliexpress-dropship/assets/146415222/0979c601-b437-4c1c-aeab-12d7bcf10c9a)
