### ISSUE TITLE
Unable to give decimal values in price in configuration 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/laravel-aliexpress-dropship#11]
unable to give decimal values  in custom price, increase or decrease.

**Comment by bhanu-webkul** [comment]
Framework Version: 0.1.8

not able to give any value after selecting custom price 

![Screenshot (84)](https://user-images.githubusercontent.com/52821836/68833968-b8208e80-06da-11ea-8521-97fafcd6a4cd.png)

**Comment by jyoti-webkul** [comment]
- Fixed

---------------------

![Screenshot (26)](https://user-images.githubusercontent.com/45203177/84027475-a7a07000-a9ac-11ea-892e-e6b3525c75e6.png)
