### ISSUE TITLE
Imported product color is not visible on store.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/laravel-aliexpress-dropship#24]
![Screenshot (22)](https://user-images.githubusercontent.com/45203177/84019716-4de57900-a99f-11ea-93a6-726e89b13721.png)
![Screenshot (21)](https://user-images.githubusercontent.com/45203177/84019722-4f16a600-a99f-11ea-8e80-fc9a589afea4.png)

**Comment by prateek-webkul** [comment]
@jyoti-webkul , Please provide the product url, as not getting issue for other products
![Screenshot from 2020-06-09 17-00-12](https://user-images.githubusercontent.com/48429511/84142908-4394af00-aa73-11ea-9154-06679eb60edf.png)
