### ISSUE TITLE
Price increase functionality not working.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/laravel-aliexpress-dropship#26]
![Screenshot (23)](https://user-images.githubusercontent.com/45203177/84025815-d537ea00-a9a9-11ea-8dd0-a40ea66bc5fd.png)

![Screenshot (24)](https://user-images.githubusercontent.com/45203177/84025936-06b0b580-a9aa-11ea-9b7d-201a7f54d098.png)

![Workspace 1_043](https://user-images.githubusercontent.com/45203177/84026083-48416080-a9aa-11ea-8fe2-edb3db5ce495.png)

**Comment by prateek-webkul** [comment]
@jyoti-webkul , same issue (https://github.com/bagisto/laravel-aliexpress-dropship/issues/42)
