### ISSUE TITLE
sku is not showing in main product at admin end 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/laravel-aliexpress-dropship#32]
https://prnt.sc/t60j9s

**Comment by prateek-webkul** [comment]
@bhanu-webkul ,
provide the product which generate the issue, as tested with product (https://www.aliexpress.com/item/4000109612070.html?spm=a2g01.12617084.fdpcl001.1.247dPw6KPw6K3D&gps-id=5547572&scm=1007.19201.130907.0&scm_id=1007.19201.130907.0&scm-url=1007.19201.130907.0&pvid=e0004032-8bdd-40c1-99ed-2f0cf15a852c) didn't get issue... (see attachment)

![Screenshot from 2020-07-01 21-52-39](https://user-images.githubusercontent.com/48429511/86268048-3c317300-bbe5-11ea-8c4e-3852604133bb.png)

**Comment by bhanu-webkul** [comment]
@prateek-webkul 
Please look at my screen shot again, I have shown for dropship manager grid, and you are checking for catalog grid

**Comment by bhanu-webkul** [comment]
https://www.aliexpress.com/item/4000224264587.html?spm=a2g0o.productlist.0.0.46951018W6k8K8&algo_pvid=42ded0ad-75ec-4d92-afa0-24bba521d73a&algo_expid=42ded0ad-75ec-4d92-afa0-24bba521d73a-0&btsid=0ab50a5715936641838542585ec353&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

**Comment by jyoti-webkul** [comment]
- Fixed

----------------------

![Workspace 1_460](https://user-images.githubusercontent.com/45203177/97995212-3d311600-1e0c-11eb-9312-935344174746.png)
