### ISSUE TITLE
issue on importing product in arabic locale 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/laravel-aliexpress-dropship#34]
https://prnt.sc/t63p7i

**Comment by prateek-webkul** [comment]
@bhanu-webkul, 
provide the steps to generate the issue..

**Comment by bhanu-webkul** [comment]
set default locale to arabic at admin end and then import the product, you will see name is missing in main product- https://prnt.sc/ta7s46

**Comment by jyoti-webkul** [comment]
- Fixed

------------------------------

![Workspace 1_463](https://user-images.githubusercontent.com/45203177/98020023-7ecfba00-1e28-11eb-8e7b-c6c798b513bf.png)
