### ISSUE TITLE
if admin imports a product from en(aliexpress) to ar, there is issues 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/laravel-aliexpress-dropship#39]
vairants are coming multiple time in product section of dropship manager
https://prnt.sc/t6preq
variants img are wrong on front end
https://prnt.sc/t6pr1f

https://www.aliexpress.com/item/4001078097151.html?spm=a2g0o.productlist.0.0.5f013afbhDIILs&algo_pvid=d23e2ef3-d6b0-4d91-9416-3cb9066172ee&algo_expid=d23e2ef3-d6b0-4d91-9416-3cb9066172ee-0&btsid=0ab50a5715931500688931928e8a96&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

**Comment by bhanu-webkul** [comment]
Even no variants are displaying - https://prnt.sc/ta7wcv

**Comment by jyoti-webkul** [comment]
- Fixed

------------------
