### ISSUE TITLE
Dropship package configuration issues

### ISSUE THREAD

**Issue by WendK** [bagisto/laravel-aliexpress-dropship#41]
Hello there,
I am using bagisto v1.1.2.  Here are some of the issues that have.
**1st Issue:** In the dropship configuration page under "Product Price" accordion, the input fields "Custom Price," "Increase (%)," and "Decrease (%) " are all inactive. I had the same Issue with the laravel-6-compatible version. That is the main reason why I move to bagisto version 1.1.2.
**2nd Issue:** the dropship icon doesn't appear in the fare left navbar.
**3rd Issue:** the package is still using the fire() method of Laravel Event class, causing an error when trying to fetch product information using the chrome extension. fire() should be replaced with dispatch() on the "Order Repository" and the "Product Repository." I did that on my end, and it fixed the error. However, the chrome extension is not able to pull most products' (99.99%) data from AliExpress. I got the following error message: "Warning: there is some error to fetch product data, please try it again". The only product for which I was able to fetch the data could not be imported into my website. I got the following error message: "Warning: product could not be imported successfully and next process like variations and reviews could not be imported, please try it again." Note that I downloaded the chrome extension from your Github because the one on google extensions store is not working at all.
Please let me know when you fix these issues

**Comment by prateek-webkul** [comment]
Hey @WendK ,

We have fixed all the issues listed by you, please get the latest pull from v1.1.0 branch...

**Comment by WendK** [comment]
Thanks! I'll check it out and let you know it went.

**Comment by WendK** [comment]
Per @vaishaliwebkul comment, I reinstall Bagisto v1.1.2 and [laravel aliexpress dropship v1.1.0](https://github.com/bagisto/laravel-aliexpress-dropship/tree/v1.1.0). This corrected the styling problem on the configuration page. However, the "Product Price" configuration options' input fields do not accept any input, regardless of the option I choose (Increase, Decrease, or Custome price). 
![Screenshot (130)](https://user-images.githubusercontent.com/43703630/86322277-8ae40a80-bbef-11ea-8cf1-3973275fa562.png)
When I remove one of the event listeners using Google Chrome developer tools, I was able to type in a number. So, the problem seems to be JavaScript related.
![Screenshot (134)](https://user-images.githubusercontent.com/43703630/86323448-b8ca4e80-bbf1-11ea-851d-e647c6eb11c2.png)

Secondly, I am still getting the following error message: "Warning: product could not be imported successfully and next process like variations and reviews could not be imported, please try it again," when I try to import a product.
![Screenshot (133)](https://user-images.githubusercontent.com/43703630/86322747-62104500-bbf0-11ea-8bd1-4ec63cec1ba4.png)

**Comment by bhanu-webkul** [comment]
@WendK 
Yes we are working to fix 1st issue asap, 
For the second issue, could you please  do a favour by providing product link, so that we check for that because we are able to import other products. - https://prnt.sc/ta8u0c

**Comment by WendK** [comment]
I was not able to import any product yet. Here are some products links:

https://www.aliexpress.com/item/4000177492201.html?spm=a2g0o.productlist.0.0.49716be4FOq6yX&algo_pvid=c9549ab5-10bd-49c2-b8ba-c3a5c898df86&algo_expid=c9549ab5-10bd-49c2-b8ba-c3a5c898df86-7&btsid=0ab6fa8115936750565733462efcce&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

https://www.aliexpress.com/item/4000317500487.html?spm=a2g0o.productlist.0.0.49716be4FOq6yX&algo_pvid=c9549ab5-10bd-49c2-b8ba-c3a5c898df86&algo_expid=c9549ab5-10bd-49c2-b8ba-c3a5c898df86-46&btsid=0ab6fa8115936750565733462efcce&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

https://www.aliexpress.com/item/4000542223770.html?spm=a2g0o.productlist.0.0.dd316be4UMyCnE&algo_pvid=f3b4ba0f-9cdc-467f-9848-0114c068346d&algo_expid=f3b4ba0f-9cdc-467f-9848-0114c068346d-3&btsid=0ab50f4415936754113902976e4f98&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

https://www.aliexpress.com/item/4001112960755.html?spm=a2g0o.productlist.0.0.dd316be4UMyCnE&algo_pvid=f3b4ba0f-9cdc-467f-9848-0114c068346d&algo_expid=f3b4ba0f-9cdc-467f-9848-0114c068346d-45&btsid=0ab50f4415936754113902976e4f98&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

**Comment by bhanu-webkul** [comment]
@WendK 

I have tried to import all 4 products from above link and  i did not find any trouble while importing them.
https://prnt.sc/tacdm0 , https://prnt.sc/tackpd

**Comment by WendK** [comment]
Are you using the same versions as the ones I am using (bagisto v1.1.2 and AliExpress dropship v1.1.0)?  If So How Can I get mine to work besides the issue of product price configuration?

**Comment by prateek-webkul** [comment]
@WendK, what issues are you facing can you attach some screenshots ?

**Comment by WendK** [comment]
> @WendK, what issues are you facing can you attach some screenshots?

The main issue I am facing ing is that after installation and configuration, I am not able to import products from AliExpress. Here is what I did:

1. I downloaded Bagisto v1.1.2 master branch and unzip the folder, uploaded it to the server, and installed it. following are the steps:
    - I configured the .env file
    - I ssh to my server and run: composer install
    - then run: php artisan key:generate
    - then run: php artisan migrate
    - then: php artisan db:seed
    - then : php artisan vendor:publish
                -> Press 0 and then press enter to publish all assets and configurations.
     - then: php artisan storage:link (but this command gave the following message: symlink was deactivated for security reasons)
Because my server is a shared hosting, I copied the content of public folder to public_html folder, then, openned index.php folder to correct the path to .env file and to the bootstrap folder.

2. I then downloaded laravel aliexpress dropship v1.1.0 tree branch and unzip the folder, uploaded it to the server, merge the "dropship" folder into "packages/webkul" folder, and run following commands:
    - I went to config/app.php file and added the following line under 'providers'
         Webkul\Dropship\Providers\DropshipServiceProvider::class 
    - then, I went to composer.json file and added the following line under 'psr-4'
        "Webkul\\Dropship\\": "packages/Webkul/Dropship"
    - then run: composer dump-autoload
    - then: php artisan migrate
    - then: php artisan route:cache
    - then: php artisan vendor:publish
                -> Press 0 and then press enter to publish all assets and configurations.
    - then: composer require symfony/dom-crawler

After these steps, everything seems to be correctly installed. I went to the admin dashboard and did all the configurations. Except for the "Product Price" configuration that was not working, because the value input field for the options (Increase, Decrease, or Custom Price) wasn't accepting any input, I did all other configurations. When I tried then to import products from aliexpress, I always getting errors (I already write about these errors, my posts before this one).

The chrome extension I am using is the one I downloaded from your GitHub repository because the one on google extensions web store is not active on aliexpress products page when I tried to use it.

Did I miss a step in the installation process? Aliexpress droshipping is just not working for me. Though, it is the reason why I wanted to give Bagisto a try.

**Comment by bhanu-webkul** [comment]
@WendK 

please raise the ticket for same at https://bagisto.uvdesk.com/en/customer/create-ticket/

**Comment by WendK** [comment]
I found out why it was not working. I was using Bagisto the active master branch instead of the tree v1.1.2. The problem I had was solved when I reinstalled the project using the tree v1.1.2. Thanks for answering my questions.

**Comment by bhanu-webkul** [comment]
@WendK 

Great!!! Really appreciate your efforts. 

Let us know in case if any further assistance needed anytime in future.

**Comment by WendK** [comment]
I will!
