### ISSUE TITLE
Product Price configuration options' input fields do not accept any input

### ISSUE THREAD

**Issue by WendK** [bagisto/laravel-aliexpress-dropship#42]
The "Product Price" configuration options' input fields do not accept any input, regardless of the option I choose (Increase, Decrease, or Custome price). 

![Screenshot (130)](https://user-images.githubusercontent.com/43703630/86322277-8ae40a80-bbef-11ea-8cf1-3973275fa562.png)

When I remove one of the event listeners using Google Chrome developer tools, I was able to type in a number. So, the problem seems to be JavaScript related. 

![Screenshot (134)](https://user-images.githubusercontent.com/43703630/86323448-b8ca4e80-bbf1-11ea-851d-e647c6eb11c2.png)

Can you please look into it?

**Comment by jyoti-webkul** [comment]
- Fixed

-------------------------
![Workspace 1_464](https://user-images.githubusercontent.com/45203177/98083088-d0675b80-1e9f-11eb-876c-e35a042bce68.png)
