### ISSUE TITLE
Could not open input file: artisan

### ISSUE THREAD

**Issue by JESUDAWN** [bagisto/laravel-aliexpress-dropship#45]
Please help
I cloned the laravel dropship.
I can change directory to it but when I run php artisan serve it shows -Could not open input file: artisan

My LORD JESUS CHRIST bless you, hoping you believe In HIM

**Comment by prateek-webkul** [comment]
Hello @JESUDAWN ,

Please run the command "php artisan serve" from the root of your project...

Thanks

**Comment by JESUDAWN** [comment]
That's what I did at the directory,
Laravel-aliexpress-dropship

**Comment by prateek-webkul** [comment]
Can you share the screenshot where you are running the command (php artisan serve)...

**Comment by JESUDAWN** [comment]
That's the screenshot attached.

**Comment by prateek-webkul** [comment]
Screenshot not attached. Please once check again....

**Comment by prateek-webkul** [comment]
Hi @JESUDAWN 

This issue has been opened for more than a month. And, it seems that your issue is resolved. Therefore, I am closing the issue.

Thanks
