### ISSUE TITLE
track tracking number to customer

### ISSUE THREAD

**Issue by wilsden** [bagisto/laravel-aliexpress-dropship#53]
Add a track number so that it will be sent by mail to the client, after processing the order, according to the status "sent"

**Comment by prateek-webkul** [comment]
Hello @wilsden ,

We already have the functionality such that if customer completes the order the mail is sent to customer with order details.

Thanks

**Comment by prateek-webkul** [comment]
@wilsden,

We are closing the issue as it seems your issue has been resolved with the above replies. If still, you have any issues feel free to open the issue.
