### ISSUE TITLE
Error In ProviderRepository.php line 208

### ISSUE THREAD

**Issue by macano13** [bagisto/laravel-aliexpress-dropship#54]
Hi,

I tried to install dropship aliexpress module but i get error  after  I have used this command : 
"composer dump-autoload"

this is the error message:
```
In ProviderRepository.php line 208:
Class 'Webkul\Dropship\src\Providers\DropshipServiceProvider' not found
```

Can someone please help me with this ?

**Comment by prateek-webkul** [comment]
Hey @macano13 ,

You need to upload the dropship package under "packages/Webkul" directory, so it can load it from there.

Thanks

**Comment by macano13** [comment]
> Hey @macano13 ,
> 
> You need to upload the dropship package under "packages/Webkul" directory, so it can load it from there.
> 
> Thanks

Hi,

Yes, that is exactly what I did.  I downloaded dropship module from the link below:
https://store.webkul.com/bagisto-aliexpress-dropship.html 

and follow this guide here : 
https://webkul.com/blog/laravel-aliexpress-dropshipping/

and I extracted directory called "packages" into the  root directory of bagisto
Please check the image below : 

![bagisto-2](https://user-images.githubusercontent.com/42044350/103215419-92247080-4913-11eb-8e0c-7662a8b22c2d.png)


is that correctly done ?

Best regards

**Comment by prateek-webkul** [comment]
yes, the package in downloaded correctly. Please once check that is the dropship package is setup correctly or not .

**Note:** You may refer the link https://github.com/bagisto/laravel-aliexpress-dropship#3-installation

**Comment by macano13** [comment]
I fix it, and yes its better to use that installation guide and download files from that source.

Best regards
