### ISSUE TITLE
Product variation images are not importing with variants

### ISSUE THREAD

**Issue by musawirjon** [bagisto/laravel-aliexpress-dropship#57]
Hello @shubhwebkul @prateek-webkul and team,
I am importing products from aliexpress, Products are importing perfectly but all the variants like description and images are missing due to this on front end changing variants images and other details are not showing for the product variant accept prices that are changing with variation changes.

screenshot #1: wthout choosing variants
https://prnt.sc/yhpn5a

screenshot #2 Price changed but other details like image in the slider and variant description are not updating
https://prnt.sc/yhpsnt

Please have a look into it.

**Comment by prateek-webkul** [comment]
@musawirjon ,

We are checking for this issue and will revert ASAP issue got fixed.

**Comment by musawirjon** [comment]
Hello @prateek-webkul  thank you for taking notice of it.
Please make it to bring images and description url key etc. Will be very useful if this work is done.

**Comment by musawirjon** [comment]
Also I have one other quetion of the topic. 
Is their any possibility for tracking orders. Like I want ability for customers to track their orders. Do I consult this thing with bagisto or it something that is possible by dropship module.

**Comment by prateek-webkul** [comment]
Hello @musawirjon,

For the issue, we will continue to communicate over the ticket raised by you... 

Thanks

**Comment by prateek-webkul** [comment]
Implemented
