### ISSUE TITLE
unable to import products from aliexpress

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/laravel-aliexpress-dropship#63]
https://www.aliexpress.com/item/1005001631840988.html?spm=a2g0o.productlist.0.0.119469ediEvKMh&algo_pvid=a4dcf373-6fa0-4364-93e9-cb44c6f4f647&algo_expid=a4dcf373-6fa0-4364-93e9-cb44c6f4f647-2&btsid=0b0a555516160549149265959eaa1c&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

![Screenshot from 2021-03-18 13-17-00](https://user-images.githubusercontent.com/52821836/111594320-ed6a4e80-87f0-11eb-82be-9fdc114dc9ac.png)

**Comment by prateek-webkul** [comment]
imported product from above link..**Working fine** https://prnt.sc/1231hfz

**Comment by bhanu-webkul** [comment]
working fine
