### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by ogbuechi** [bagisto/laravel-aliexpress-dropship#65]
unable to install, i got 
 bagisto/aliexpress-dropship dev-master requires symfony/dom-crawler ^5.3 -> found symfony/dom-crawler[v5.3.0-BETA1, ..., 5.4.x-dev] but the package is fixed to v5.2.4 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by ghermans** [comment]
This should be fixed, please let us know if you still encounter this issue

**Comment by fahedaljghine** [comment]
@ghermans I am getting this issue
