### ISSUE TITLE
Error::("Class 'Webkul\Core\Eloquent\Repository' not found")

### ISSUE THREAD

**Issue by WenderT** [bagisto/laravel-aliexpress-dropship#7]
`composer dump-autoload
Generating optimized autoload files> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   ReflectionException  : Class Webkul\Dropship\Repositories\AliExpressProductRepository does not exist

  at C:\Users\bugch\Desktop\artur_shop\shop\vendor\laravel\framework\src\Illuminate\Container\Container.php:855
    851|
    852|             // If the class is null, it means the dependency is a string or some other
    853|             // primitive type which we can not resolve since it is not a class and
    854|             // we will just bomb out with an error since we have no-where to go.
  > 855|             $results[] = is_null($dependency->getClass())
    856|                             ? $this->resolvePrimitive($dependency)
    857|                             : $this->resolveClass($dependency);
    858|         }
    859|

  Exception trace:

  1   Error::("Class 'Webkul\Core\Eloquent\Repository' not found")
      C:\Users\bugch\Desktop\artur_shop\shop\packages\Webkul\Dropship\src\Repositories\AliExpressProductRepository.php:22

  2   include()
      C:\Users\bugch\Desktop\artur_shop\shop\vendor\composer\ClassLoader.php:444

  Please use the argument -v to see more details.
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1`

**Comment by prateek-webkul** [comment]
Hi @WenderT 
Once Run the following command:
1) php artisan config:cache
2)composer dump-autoload

And, still if some issue remains you need to install bagisto again

Thanks

**Comment by prateek-webkul** [comment]
Hi WenderT,

This issue has been opened for more than a month. And, it seems that your issue is resolved. Therefore, I am closing the issue.

Thanks
