### ISSUE TITLE
Images are not showing on the color section of the product page 

### ISSUE THREAD

**Issue by Nikitajoshi39** [bagisto/laravel-aliexpress-dropship#78]
**Bagisto:v1.3.2
Laravel-aliexpress-dropship:master**

**Steps to reproduce--**
1. Go to the demo front 
2. Select product -> view product page -> color section  -> images are not showing 

**Image:**
![color](https://user-images.githubusercontent.com/92033944/148213569-0e19e9ae-87e0-486b-8634-d149eee20ea4.png)

**Comment by Meraj-Webkul** [comment]
All Images are showing properly in product page.
